### PR TITLE
ui. improve logs view

### PR DESCRIPTION
**Pull request by federicoballarini**
Improve fail2ban logs view and fix package vulnerabilites.
Refer to https://github.com/NethServer/dev/issues/6005

### CODE REVIEW

**Comment by federicoballarini** [comment]
Waiting for review.

**Comment by stephdl** [comment]
will try to check tomorrow

**Comment by edospadoni** [comment]
With this change: `@vue/cli-service": "^4.1.1` have you tryied if `npm run watch` and `npm run build` run smoothly?

**Comment by federicoballarini** [comment]
> With this change: `@vue/cli-service": "^4.1.1` have you tryied if `npm run watch` and `npm run build` run smoothly?

Seems to work fine

**Pull request merged**
