### PR TITLE
Use perl DBI to retrieve the number of ban

### PR DESCRIPTION
**Pull request by stephdl**
perl DBI seems to do a better stable connection to the database rather than the bash script

https://github.com/NethServer/dev/issues/6253

### CODE REVIEW

**Review by DavidePrincipi — COMMENTED** [review]
As alternative to the Perl driver, did you try to set a _timeout_ for sqlite3?

From the `sqlite3` man page

>        .timeout MS            Try opening locked tables for MS milliseconds

As the issue is in the way sqlite3 access the DB file, I'm afraid changing the script implementation might introduce unpredictable conditions (although they could be favourable).

**Comment by stephdl** [comment]
> As alternative to the Perl driver, did you try to set a timeout for sqlite3?

Not really indeed, but I am not really confident to call bash command inside perl `open`, sometimes it might work or also sometimes fail.

This is not really easy to reproduce, only one of my 3 servers did it, @filippocarletti  saw it also. I would be curious if we could find it also in NethEnterprise.

**Comment by DavidePrincipi** [comment]
> Not really indeed, but I am not really confident to call bash command inside perl `open`, sometimes it might work or also sometimes fail.

We could improve the  `open()` invocation with `qw()` as seen elsewhere...

> This is not really easy to reproduce, only one of my 3 servers did it, @filippocarletti saw it also. I would be curious if we could find it also in NethEnterprise.

I reproduce it easily on my router after a few seconds of this loop:

```text
[root@nsec-primary system]# time while /usr/bin/sqlite3 -list  /var/lib/fail2ban/fail2ban.sqlite3  "select jail, count(*) as count from bans  WHERE date(datetime(timeofban , 'unixepoch')) = date('now') group by jail;" >/dev/null; do : ; done
Error: database is locked

real    0m3.364s
user    0m1.965s
sys     0m1.479s
```

If I add a `-cmd ".timeout 1000"` option the script is still running after 45 secs:

```text
[root@nsec-primary system]# time while /usr/bin/sqlite3 -list  /var/lib/fail2ban/fail2ban.sqlite3 -cmd ".timeout 1000"  "select jail, count(*) as count from bans  WHERE date(datetime(timeofban , 'unixepoch')) = date('now') group by jail;" >/dev/null; do : ; done
^CError: interrupted

real    0m45.120s
user    0m26.402s
sys     0m19.994s
```

I suggest to 

- revert the DBI change 
- add a `-cmd ".timeout 1000"` argument to the sqlite3 command line
- refactor the `open()` with `qw()` to try the _list form_ invocation style https://perldoc.perl.org/functions/open.html

**Comment by stephdl** [comment]
No luck for me

```
[root@NS7 ~]# time while /usr/bin/sqlite3 -list  /var/lib/fail2ban/fail2ban.sqlite3 -cmd ".timeout 1000"  "select jail, count(*) as count from bans  WHERE date(datetime(timeofban , 'unixepoch')) = date('now') group by jail;" >/dev/null; do : ; done
^CError: interrupted

real	1m3.329s
user	0m34.784s
sys	0m30.233s
[root@NS7 ~]# time while /usr/bin/sqlite3 -list  /var/lib/fail2ban/fail2ban.sqlite3  "select jail, count(*) as count from bans  WHERE date(datetime(timeofban , 'unixepoch')) = date('now') group by jail;" >/dev/null; do : ; done
^CError: interrupted

real	2m13.340s
user	1m13.613s
sys	1m2.590s

```

I can try to increase the timout the changes are thinner but I am not sure it could help

**Comment by stephdl** [comment]
obsoleted by https://github.com/NethServer/nethserver-fail2ban/pull/94

**Pull request closed without merging**
